# Site settings
title: "Ali Tai"
email: alictai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "PM passionate about design, customers, and results"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alictai.github.io" # the base hostname & protocol for your site
twitter_username: alitai
github_username:  alictai

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"

# Plugins
plugins:
 - jekyll-paginate